version: "3.8"

services:
  spark:
    container_name: ras-spark
    #image: docker.io/bitnami/spark:3.5.0
    image: docker.io/bitnami/spark
    volumes:
      - ./data:/opt/bitnami/spark/data/
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - '8080:8080'
      - "4040:4040"
  spark-worker-1:
    container_name: ras-spark-worker-1
    #image: docker.io/bitnami/spark:3.5.0
    image: docker.io/bitnami/spark
    volumes:
      - ./data:/opt/bitnami/spark/data/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - "8081:8081"
      - "4041:4040"
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PUBLIC_DNS=localhost
  spark-worker-2:
    container_name: ras-spark-worker-2
    #image: docker.io/bitnami/spark:3.5.0
    image: docker.io/bitnami/spark
    volumes:
      - ./data:/opt/bitnami/spark/data/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - "8082:8082"
      - "4042:4040"
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PUBLIC_DNS=localhost
